version: '3.7'
services:
  db:
    container_name: ekino-db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
    - "3319:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker-root
      MYSQL_DATABASE: ekino
      MYSQL_USER: root
      MYSQL_PASSWORD: docker-root
  flyway:
    image: boxfuse/flyway:5.2.1
    command: -url=jdbc:mysql://db -schemas=ekino -user=root -password=docker-root -connectRetries=60 migrate
    volumes:
    - ./db:/flyway/sql
    depends_on:
    - db
  php:
    container_name: ekino-php
    build: ./docker/php-fpm
    ports:
    - "9000:9001"
    volumes:
    - .:/var/www/symfony:cached
    - ./logs/symfony:/var/www/symfony/var/log:cached
    links:
    - db
    extra_hosts:
    - "docker.host:127.0.0.1"
  nginx:
    container_name: ekino-nginx
    build: ./docker/nginx
    ports:
    - "8070:80"
    links:
    - php
    volumes:
    - ./logs/nginx:/var/log/nginx:cached
    - .:/var/www/symfony:cached
