-- MySQL Script generated by MySQL Workbench
-- Sun Jan 13 12:37:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ekino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ekino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ekino` DEFAULT CHARACTER SET utf8 ;
USE `ekino` ;

-- -----------------------------------------------------
-- Table `ekino`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekino`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL,
  `date_add` DATETIME NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekino`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekino`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `age` VARCHAR(45) NULL,
  `date_add` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekino`.`programme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekino`.`programme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATETIME NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekino`.`showing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekino`.`showing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATETIME NULL,
  `time_show` TIME NULL,
  `programme_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`, `programme_id`, `movie_id`),
  INDEX `fk_showing_programme1_idx` (`programme_id` ASC),
  INDEX `fk_showing_film1_idx` (`movie_id` ASC),
  CONSTRAINT `fk_showing_programme1`
    FOREIGN KEY (`programme_id`)
    REFERENCES `ekino`.`programme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_showing_film1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `ekino`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ekino`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ekino`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATETIME NULL,
  `date_booking` DATETIME NULL,
  `user_id` INT NOT NULL,
  `seat_number` TINYINT NULL,
  `status` TINYINT NULL,
  `showing_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `showing_id`),
  INDEX `fk_booking_user1_idx` (`user_id` ASC),
  INDEX `fk_booking_showing1_idx` (`showing_id` ASC),
  CONSTRAINT `fk_booking_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ekino`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_showing1`
    FOREIGN KEY (`showing_id`)
    REFERENCES `ekino`.`showing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
