/*
-- Query: SELECT * FROM ekino.movie
LIMIT 0, 1000

-- Date: 2019-01-26 21:03
*/
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (1,'BOHEMIAN RHAPSODY','Porywająca opowieść o zespole Queen, jego muzyce i niezwykłym wokaliście Freddie’em Mercurym, który przełamując stereotypy i konwencje, zdobył uwielbienie niezliczonych fanów. Film ukazuje błyskotliwą karierę zespołu, który dzięki ikonicznym utworom i rewolucyjnemu brzmieniu wspiął się na szczyty sławy, dopóki skandalizujący styl życia Mercury’ego nie postawił wszystkiego pod znakiem zapytania. Triumfalny powrót zespołu podczas koncertu na rzecz Live Aid z udziałem cierpiącego na śmiertelną chorobę Mercury’ego wszedł na trwałe do historii muzyki rockowej i po dziś dzień stanowi źródło inspiracji dla wszystkich tych, którzy czują się inni, niepoprawnych marzycieli i wielbicieli muzyki na całym świecie.','12','2019-01-26 00:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (2,'WIĘCEJ INFORMACJI O DIABLO. WYŚCIG O WSZYSTKO','Pasją Kuby są szybkie samochody, zawrotna prędkość i ekstremalne wyścigi. Jego siostra Lena musi przejść bardzo kosztowną operację za granicą. Chcąc zdobyć potrzebne środki, chłopak postanawia brać udział w nielegalnych rajdach. Talent i brawurę młodego kierowcy zauważa wpływowy gangster – Max. Proponuje chłopakowi udział w okrytym złą sławą wyścigu, który niejeden kierowca przypłacił kalectwem, a nawet życiem. Nagrodą dla zwycięzcy legendarnych zmagań jest tytuł „Diablo” i kilkaset tysięcy euro. Kuba podejmuje ryzyko i wkracza do podejrzanego świata wielkich pieniędzy, pięknych kobiet i szemranych interesów. To właśnie w nim poznaje Ewę – obdarzoną wyjątkową urodą, nieugiętą zawodniczkę, która z zaciętej rywalki staje się jego wielką namiętnością. Wkrótce na jaw wychodzi jednak prawdziwa tożsamość dziewczyny. Od tego momentu życie Kuby znajdzie się w wielkim niebezpieczeństwie.','13','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (3,'DOM, KTÓRY ZBUDOWAŁ JACK','Tytułowy Jack to nowa postać w popkulturowym klanie psychopatów, obok Kuby Rozpruwacza, Dextera czy Hannibala Lectera. Mistrz światowego kina pokazuje kilkanaście lat z życia seryjnego mordercy, piekielnie inteligentnego perfekcjonisty, pełnego sprzeczności, słabości i drobnych natręctw. Jack jest estetą, wielbicielem malarstwa, architektury, poezji i wycieczek na łono natury. Zabójca patrzy na swoje zbrodnie jak na mroczne dzieła sztuki. Jaki kształt nada swojej zbrodni doskonałej?','18','2019-01-26 09:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (4,'GLASS','Bruce Willis powraca jako David Dunn, zas Samuel L. Jackson jako Elijah Price, znany pod pseudonimem Mr. Glass. W obsadzie jest równiez James McAvoy, ponownie w roli Kevina Wendella Crumba, czlowieka o mnogiej osobowosci i Anya Taylor-Joy, jako Casey Cook – jedyna, której udalo sie ujsc z zyciem ze spotkania z Bestia. Rozwijajac zakonczenie zaprezentowane w filmie Split, Glass skupi sie na Davidzie Dunnie, który sciga nadludzkie wcielenie Crumba, prowokujac szereg niebezpiecznych spotkan. W tym samym czasie z mroku wylania sie Price, który jest w posiadaniu sekretu kluczowego dla losów obu mezczyzn. Producentami szalonej kulminacji dwóch blockbusterów sa M. Night Shyamalan, Jason Blum, Ashwin Rajan, Marc Bienstock i Steven Schneider.','15','2019-01-26 09:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (5,'KARTOTEKA 64','Czwarta, po „Kobiecie w klatce”, „Zabójcach bażantów” i „Wybawieniu”, ekranizacja bestsellerowej serii kryminałów Jussi Adler-Olsena – ulubieńca New York Times’a, pisarza stawianego przez krytykę i czytelników obok takich skandynawskich mistrzów gatunku, jak: Henning Mankell, Stieg Larsson i Jo Nesbo. Tym razem nieustraszeni detektywi z Departamentu Q podejmą się sprawy tajemniczego ośrodka, w którym na przetrzymywanych kobietach testowano nazistowskie praktyki eugeniki. Przeżywający problemy osobiste komisarz Carl Mørck przystępuje do nierozwikłanej od lat sprawy tajemniczego zaginięcia prostytutki. W toku śledztwa odkrywa, że przypadek kobiety stanowi zaledwie fragment znacznie większej układanki, dotyczącej nadużyć najgorszego rodzaju. Takich, których geneza sięga pół wieku wstecz i które prawdopodobnie nadal mają miejsce. Nadużycia seksualne, medyczne eksperymenty, przemoc i gęstniejący mrok składają się na najtrudniejszą i jak dotąd najbardziej zawikłaną sprawą w dziejach Departamentu Q.','15','2019-01-26 09:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (6,'MARIA, KRÓLOWA SZKOTÓW','„Maria, królowa Szkotów” to zapis trudnego życia charyzmatycznej Marii Stuart. W wieku 16 lat stała się królową Francji, w wieku 18 owdowiała, czując silną presję otoczenia, by ponownie wyjść za mąż. Zamiast tego Maria powraca do swej ojczystej Szkocji, by osiąść na tamtejszym, należnym jej, jak twierdzi, tronie. Tymczasem na tronie Anglii i Szkocji zasiada Elżbieta I. Młoda królowa przygląda się „siostrze” z lękiem i fascynacją. Rywalki we władzy i miłości, osamotnione kobiety w męskim świecie, muszą zdecydować, jaką strategię podejmą w grze toczącej się wokół małżeństwa i niezależności. Maria, zdecydowana być kimś więcej niż marionetka, utrzymuje, że angielski tron należy się jej, co zagraża suwerenności Elżbiety. Rebelia, zdrada, konspiracja zachwieją oboma tronami, zmieniając na zawsze kurs historii.','14','2019-01-26 09:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (7,'MISZMASZ CZYLI KOGEL MOGEL 3','„Miszmasz czyli Kogel Mogel 3” to ciąg dalszy przygód Kasi, ekscentrycznej rodziny Wolańskich i pozostałych bohaterów kultowych komedii „Кogel Mogel”. Główna bohaterka Kasia (Grażyna Błęcka-Kolska) nadal mieszka we wsi Brzózki i walczy z niechcianym zalotnikiem Staszkiem Kolasą. Do Polski wraca niespodziewanie jej syn Marcin (Nikodem Rozbicki) i od razu wpada w kłopoty. Chłopak ma pomysł na niecodzienny biznes… W tym czasie w Warszawie w rodzinie Wolańskich wybucha kryzys. Wolańska (Ewa Kasprzyk) – celebrytka i słynna sekstrenerka – wydaje kontrowersyjną książkę. Jej bliscy – mąż (Zdzisław Wardejn) i córka Agnieszka (Aleksandra Hamkało) – buntują się i uciekają z domu. Postanawiają najpierw odwiedzić Piotrusia (Maciej Zakościelny), który dziś wiedzie wygodne życie u boku żony Marleny (Katarzyna Skrzynecka). Następnie ruszają w nieznane, a finał tej wycieczki znów przejdzie do legendy!','13','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (8,'NARODZINY GWIAZDY','Cooper wciela sie w role Jacksona Maine’a, gwiazdora muzyki country, którego kariera chyli sie ku upadkowi, kiedy odkrywa utalentowana, nieznana nikomu piosenkarke Ally (w tej roli Lady Gaga). Kiedy miedzy ta dwójka wybucha plomienny romans, Jack naklania Ally do wyjscia z cienia i pomaga jej osiagnac slawe. Jednak gdy kariera Ally w szybkim tempie przycmiewa dokonania Jacka, jest mu coraz trudniej poradzic sobie z wlasna gasnaca gwiazda.','16','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (9,'NIENAWIŚĆ, KTÓRĄ DAJESZ','Starr Carter nieustannie balansuje między dwoma światami: biedną, w przeważającej części czarną dzielnicą, w której mieszka a bogatą, w większości białą szkołą, do której uczęszcza. Chwiejna równowaga między tymi światami zostaje nieodwołalnie zakłócona, gdy Starr staje się świadkiem, jak policjant śmiertelnie rani jej najlepszego przyjaciela z dzieciństwa, Khalila. W obliczu presji ze strony społeczności, Starr musi odnaleźć swój własny głos i stanąć w obronie wszystkiego, co uważa za słuszne. W wyreżyserowanej przez George’a Tillmana Jr („Siła i honor”, „Notorious”) ekranizacji bestsellerowej książki Angie Thomas wystąpili: Amandla Stenberg, Russell Hornsby, Regina Hall, Common, Anthony Mackie i Issa Rae.','15','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (10,'UNDERDOG','„Underdog” to historia inspirowana prawdziwymi wydarzeniami. Na ich podstawie powstal scenariusz autorstwa Mariusza Kuczewskiego. Borys „Kosa” Kosinski (Eryk Lubos) to zawodnik MMA, który jest u szczytu formy. W najwazniejszej walce ze swoim najwiekszym rywalem Deni Takaevem (Mamed Khalidov) popelnia blad, który przekresla jego kariere. Traci wszystko. „Underdog” to opowiesc o slabosciach i sile czlowieka, zwatpieniu, które pokonuje rodzaca sie milosc, o walce z przeciwnosciami losu i podniesieniu po upadku, poswieceniu, rodzinie i przyjazni.','15','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (11,'ZABAWA ZABAWA','40-letnia prokurator Dorota (Agata Kulesza) pije, by – jak sama mówi – „nie zwariowac”. Zaslaniajac sie immunitetem, ukrywa wszystkie wykroczenia popelnione „pod wplywem”. Skutecznie pomaga jej w tym maz, znany polityk (Marcin Dorocinski). Studentka Magda (Maria Debska) lubi ostro imprezowac, ale swietnie sie uczy i ma super prace, wiec nikt nie robi jej z tego wyrzutów. Dla szanowanej chirurg – Teresy (Dorota Kolak) kazdy pretekst jest dobry, zeby sie napic. Alkoholu nie odmawia sobie nawet w pracy, w szpitalu dzieciecym, którego jest ordynatorem. Wkrótce, w zyciu kazdej z kobiet nastapia wydarzenia, po których ich problem przybierze na sile. Czy wspierane przez rodziny i przyjaciól bohaterki zdaza go w pore pokonac?','15','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (12,'Aquamanem','Arthur Curry niechętnie staje na czele ludu podwodnego królestwa Atlantydy.','16','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (13,'Avengers: Wojna bez granic','Potężny Thanos zbiera Kamienie Nieskończoności w celu narzucenia swojej woli wszystkim istnieniom we wszechświecie. Tylko drużyna superbohaterów znanych jako Avengers może go powstrzymać.','16','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (14,'Zimna wojna','Historia wielkiej i trudnej miłości dwojga ludzi, którzy nie potrafią być ze sobą i jednocześnie nie mogą bez siebie żyć. W tle wydarzenia zimnej wojny lat 50. w Polsce, Berlinie, Jugosławii i Paryżu.','16','2019-01-26 08:00:00');
INSERT INTO ekino.`movie` (`id`,`name`,`description`,`age`,`date_add`) VALUES (15,'Spider-Man Uniwersum','Miles Morales po ukąszeniu przez radioaktywnego pająka staje do walki z nikczemnym Kingpinem. Pomogą mu w tym Spider-Menowie z innych wymiarów.','12','2019-01-26 08:00:00');
